### ISSUE TITLE
[8] MRP Reopen error

### ISSUE THREAD

**Issue by mauroanelli2017** [camptocamp/c2c-rd-addons#28]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mrp_reopen/mrp.py", line 119, in action_reopen
    wf_service = netsvc.LocalService("workflow")
NameError: global name 'netsvc' is not defined

**Comment by ferdiga** [comment]
please which branch ?

**Comment by mauroanelli2017** [comment]
8.0

**Comment by mauroanelli2017** [comment]
8.0

 

Mauro Anelli    

 

 



ICS Technologies S.r.l.

P.IVA 02240540449

Via California 32

63066 Grottammare,

Ascoli Piceno - Italy

Tel: +39 0735 61621

Fax: +39 0735 616284

 <mailto:mauro.anelli@xtechnologies.it> mauro.anelli@xtechnologies.it

www.xtechnologies.it <http://www.xtechnologies.it/> 

 

Da: Ferdinand Gassauer [mailto:notifications@github.com] 
Inviato: giovedì 8 febbraio 2018 23:34
A: camptocamp/c2c-rd-addons <c2c-rd-addons@noreply.github.com>
Cc: mauroanelli2017 <mauro.anelli@xtechnologies.it>; Author <author@noreply.github.com>
Oggetto: Re: [camptocamp/c2c-rd-addons] [8] MRP Reopen error (#28)

 

please which branch ?

**Comment by ferdiga** [comment]
I do not support 8.0 currently - to much difference to 6.1 which I use 

try to change
import openerp.netsvc
to
from openerp import netsvc, workflow

**Comment by mauroanelli2017** [comment]
done but i get this
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mrp_reopen/mrp.py", line 119, in action_reopen
    wf_service = netsvc.LocalService("workflow")
NameError: global name 'netsvc' is not defined

**Comment by ferdiga** [comment]
Here are the only lines in 8.0 referring to netsvc - it seems it is depreciated.

./server/addons/hr_expense/tests/test_journal_entries.py:2:from openerp import netsvc, workflow
./server/openerp/__init__.py:77:import netsvc
./server/openerp/addons/base/ir/ir_cron.py:135:                    netsvc.log(_logger, logging.DEBUG, 'cron.object.execute', (cr.dbname,uid,'*',model_name,method_name)+tuple(args), depth=log_depth)
./server/openerp/addons/base/ir/ir_cron.py:30:from openerp import SUPERUSER_ID, netsvc, api
./server/openerp/conf/deprecation.py:40:# If True, openerp.netsvc.LocalService() can be used to lookup reports or to
./server/openerp/conf/deprecation.py:44:# - The openerp.netsvc.LocalService() function.
./server/openerp/http.py:100:                openerp.netsvc.log(rpc_request, logging.DEBUG, '%s.%s' % (service_name, method), replace_request_password(params))
./server/openerp/http.py:123:                openerp.netsvc.log(rpc_response, logging.DEBUG, logline, result)
./server/openerp/http.py:125:                openerp.netsvc.log(rpc_request, logging.DEBUG, logline, replace_request_password(params), depth=1)
./server/openerp/netsvc.py:48:    The openerp.netsvc.LocalService() function is deprecated. It still works
./server/openerp/report/report_sxw.py:324:    openerp.netsvc.LocalService() indirection and the related
./server/openerp/service/common.py:61:    # `openerp.netsvc.Logger` class.
./server/openerp/service/server.py:811:        rpc_request = logging.getLogger('openerp.netsvc.rpc.request')
./server/openerp/tools/config.py:359:        openerp.netsvc.init_logger()
./server/openerp/tools/translate.py:166:        # find current DB based on thread/worker db name (see netsvc)
