### ISSUE TITLE
Impossible to install Stock Product Location on v8

### ISSUE THREAD

**Issue by jaronemo** [camptocamp/c2c-rd-addons#7]
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 729, in install_from_urls
    post_install_action = self.button_immediate_install(cr, uid, to_install_ids, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 755, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/opt/odoo/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/opt/odoo/openerp/tools/convert.py", line 843, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 932, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/opt/odoo/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 922, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: stock.view_normal_procurement_locations_form" while parsing /opt/odoo/.local/share/Odoo/addons/8.0/stock_product_location/product_view.xml:5, near
<record model="ir.ui.view" id="product_normal_stock_loc_form_view">
      <field name="name">view.product.normal.stock.loc.form</field>
      <field name="model">product.product</field>
      <field name="inherit_id" ref="stock.view_normal_procurement_locations_form"/>
      <field name="type">form</field>
      <field name="arch" type="xml">
        <field name="loc_rack" position="before">
          <field name="property_stock_location" domain="[('usage','=','internal')]" attrs="{'readonly':[('type','=','service')]}"/>
        </field>
      </field>
    </record>

**Comment by ferdiga** [comment]
On 2015-03-09 19:55, jaronemo wrote:

module won't work in v8 without massive redesign , as
- prodlot_id many2one
  changed to
- lot_ids may2many

sorry for the inconvenience

**Comment by jaronemo** [comment]
So there is no attempt to fix the module to operate it in a V8?

**Comment by ferdiga** [comment]
the company paying for this decided to stay on 6.1 - and will not migrate before v9 is stable.
Reason: we had to make so many overlapping modules to get stock management AND financial accounting to be usable (at least for this company) and we will not adapt all of these modules to changed stock management now and once more to changed accounting and to changed API.

**Comment by cod3monk** [comment]
could the addon then be removed from the 8.0 branch? It is missleading and breaks updates for people who used this addon on 7.0 and upgrade to 8.0.
